Repository facebookresearch/Mephisto, pull requests merged in 2021-11, with the labels that each got.

#594 Static html blueprint fix
  mephisto/abstractions/blueprints/static_html_task/source/package-lock.json
  mephisto/abstractions/blueprints/static_html_task/static_html_blueprint.py
Labels: CLA Signed

#591 Get qualified workers
  mephisto/tools/data_browser.py
  test/tools/__init__.py
  test/tools/test_data_brower.py
Labels: CLA Signed

#590 Naming changes, new customization props, and CSS enhancements to `cra-template-mephisto-review`
  packages/cra-template-mephisto-review/README.md
  packages/cra-template-mephisto-review/package.json
  packages/cra-template-mephisto-review/template/README.md
  packages/cra-template-mephisto-review/template/sample-data.csv
  packages/cra-template-mephisto-review/template/sample-data.jsonl
  packages/cra-template-mephisto-review/template/src/components/CollectionView.jsx
  packages/cra-template-mephisto-review/template/src/components/ErrorPane.js
  packages/cra-template-mephisto-review/template/src/components/ItemView.jsx
  packages/cra-template-mephisto-review/template/src/config.js
  packages/cra-template-mephisto-review/template/src/custom/.gitkeep
  packages/cra-template-mephisto-review/template/src/index.css
  packages/cra-template-mephisto-review/template/src/index.js
  packages/cra-template-mephisto-review/template/src/plugins/DefaultItemListRenderer/DefaultItemListRenderer.jsx
  packages/cra-template-mephisto-review/template/src/plugins/DefaultItemListRenderer/index.js
  packages/cra-template-mephisto-review/template/src/plugins/DefaultItemRenderer/index.js
  packages/cra-template-mephisto-review/template/src/plugins/ListViewRenderer/index.js
  packages/cra-template-mephisto-review/template/src/plugins/WordCloudItemRenderer/index.js
  packages/cra-template-mephisto-review/template/src/renderers/GridCollection/GridCollection.css
  packages/cra-template-mephisto-review/template/src/renderers/GridCollection/GridCollection.jsx
  packages/cra-template-mephisto-review/template/src/renderers/GridCollection/index.js
  packages/cra-template-mephisto-review/template/src/renderers/JSONItem/JSONItem.css
  packages/cra-template-mephisto-review/template/src/renderers/JSONItem/JSONItem.jsx
  packages/cra-template-mephisto-review/template/src/renderers/JSONItem/index.js
  packages/cra-template-mephisto-review/template/src/renderers/ListCollection/ListCollection.css
  packages/cra-template-mephisto-review/template/src/renderers/ListCollection/ListCollection.jsx
  packages/cra-template-mephisto-review/template/src/renderers/ListCollection/ListItem.jsx
  packages/cra-template-mephisto-review/template/src/renderers/ListCollection/index.js
  packages/cra-template-mephisto-review/template/src/renderers/WordCloudItem/WordCloud.css
  packages/cra-template-mephisto-review/template/src/renderers/WordCloudItem/WordCloud.jsx
  packages/cra-template-mephisto-review/template/src/renderers/WordCloudItem/WordCloudItem.jsx
  packages/cra-template-mephisto-review/template/src/renderers/WordCloudItem/index.js
  packages/cra-template-mephisto-review/template/src/renderers/index.js
  packages/cra-template-mephisto-review/template/src/utils.js
Labels: enhancement, CLA Signed, ui/ux

#585 Creating UseGoldUnit blueprint mixin
  docs/common_qualification_flows.md
  mephisto/abstractions/blueprints/mixins/screen_task_required.py
  mephisto/abstractions/blueprints/mixins/use_gold_unit.py
  mephisto/operations/supervisor.py
  mephisto/operations/task_launcher.py
Labels: CLA Signed

#603 Creating the EC2Architect
  mephisto/abstractions/architects/ec2/.gitignore
  mephisto/abstractions/architects/ec2/__init__.py
  mephisto/abstractions/architects/ec2/cleanup_ec2_resources.py
  mephisto/abstractions/architects/ec2/ec2_architect.py
  mephisto/abstractions/architects/ec2/ec2_helpers.py
  mephisto/abstractions/architects/ec2/fallback_server/README.md
  mephisto/abstractions/architects/ec2/fallback_server/access_logs/README.md
  mephisto/abstractions/architects/ec2/fallback_server/app.py
  mephisto/abstractions/architects/ec2/fallback_server/fallback.service
  mephisto/abstractions/architects/ec2/fallback_server/scripts/first_setup.sh
  mephisto/abstractions/architects/ec2/fallback_server/scripts/run_server.sh
  mephisto/abstractions/architects/ec2/fallback_server/templates/landing.html
  mephisto/abstractions/architects/ec2/keypairs/README.md
  mephisto/abstractions/architects/ec2/prepare_ec2_servers.py
  mephisto/abstractions/architects/ec2/run_scripts/flask/init_server.sh
  mephisto/abstractions/architects/ec2/run_scripts/flask/router.service
  mephisto/abstractions/architects/ec2/run_scripts/flask/run_server.sh
  mephisto/abstractions/architects/ec2/run_scripts/node/init_server.sh
  mephisto/abstractions/architects/ec2/run_scripts/node/router.service
  mephisto/abstractions/architects/ec2/run_scripts/node/run_server.sh
  mephisto/abstractions/architects/ec2/servers/README.md
  mephisto/abstractions/blueprints/static_html_task/static_html_blueprint.py
  mephisto/operations/registry.py
  mephisto/tools/scripts.py
Labels: CLA Signed

#606 Cleanup IP race condition on EC2Architect
  mephisto/abstractions/architects/ec2/ec2_architect.py
  mephisto/abstractions/architects/ec2/ec2_helpers.py
  mephisto/abstractions/architects/ec2/fallback_server/app.py
  mephisto/abstractions/architects/ec2/prepare_ec2_servers.py
Labels: CLA Signed

#608 Relax peer deep requirements for mephisto-review-hook
  packages/mephisto-review-hook/package.json
Labels: CLA Signed

#609 EC2Architect - Various small improvements
  mephisto/abstractions/architects/ec2/ec2_architect.py
  mephisto/abstractions/architects/ec2/ec2_helpers.py
Labels: CLA Signed

#612 Documentation for the Mephisto Review CLI and front-end build work
  docs/web/docs/contributors/development.md
  docs/web/docs/explanations/architecture_overview.md
  docs/web/docs/guides/how-tos/_category_.yml
  docs/web/docs/guides/how-tos/common_qualification_flows.md
  docs/web/docs/guides/how-tos/config_faq.md
  docs/web/docs/guides/how-tos/docker.md
  docs/web/docs/guides/how-tos/front_end_faqs.md
  docs/web/docs/guides/quickstart.md
  docs/web/docs/reference/overview.md
  docs/web/docs/tutorials/review-cli.md
  docs/web/docusaurus.config.js
  docs/web/sidebars.js
  docs/web/src/pages/index.js
Labels: documentation, CLA Signed
