Repository facebookresearch/Mephisto, pull requests merged in 2021-08, with the labels that each got.

#437 Deprecate old initializers
  examples/simple_static_task/examine_results.py
  mephisto/VERSION
  mephisto/abstractions/databases/local_singleton_database.py
  mephisto/abstractions/providers/mock/mock_agent.py
  mephisto/abstractions/providers/mock/mock_requester.py
  mephisto/abstractions/providers/mock/mock_unit.py
  mephisto/abstractions/providers/mock/mock_worker.py
  mephisto/abstractions/providers/mturk/mturk_agent.py
  mephisto/abstractions/providers/mturk/mturk_provider.py
  mephisto/abstractions/providers/mturk/mturk_requester.py
  mephisto/abstractions/providers/mturk/mturk_unit.py
  mephisto/abstractions/providers/mturk/mturk_worker.py
  mephisto/abstractions/providers/mturk/utils/script_utils.py
  mephisto/abstractions/providers/mturk_sandbox/sandbox_mturk_requester.py
  mephisto/abstractions/providers/mturk_sandbox/sandbox_mturk_worker.py
  mephisto/abstractions/test/architect_tester.py
  mephisto/abstractions/test/blueprint_tester.py
  mephisto/abstractions/test/crowd_provider_tester.py
  mephisto/abstractions/test/data_model_database_tester.py
  mephisto/abstractions/test/utils.py
  mephisto/client/api.py
  mephisto/data_model/agent.py
  mephisto/data_model/assignment.py
  mephisto/data_model/db_backed_meta.py
  mephisto/data_model/project.py
  mephisto/data_model/qualification.py
  mephisto/data_model/requester.py
  mephisto/data_model/task.py
  mephisto/data_model/task_run.py
  mephisto/data_model/unit.py
  mephisto/data_model/worker.py
  mephisto/operations/operator.py
  mephisto/operations/supervisor.py
  mephisto/operations/task_launcher.py
  mephisto/scripts/local_db/load_data_to_mephisto_db.py
  mephisto/scripts/mturk/print_outstanding_hit_status.py
  mephisto/tools/data_browser.py
  mephisto/tools/misc.py
  test/abstractions/blueprints/test_mock_blueprint.py
  test/abstractions/providers/mturk/test_mturk.py
  test/core/test_supervisor.py
  test/core/test_task_launcher.py
Labels: CLA Signed

#504 Updating dates
  mephisto/data_model/agent.py
  mephisto/data_model/assignment.py
  mephisto/data_model/project.py
  mephisto/data_model/qualification.py
  mephisto/data_model/requester.py
  mephisto/data_model/task.py
  mephisto/data_model/task_run.py
  mephisto/data_model/unit.py
  mephisto/data_model/worker.py
Labels: CLA Signed

#493 Add a Storybook for the annotation-toolkit
  .pre-commit-config.yaml
  docs/storybook/.gitignore
  docs/storybook/.storybook/BrandTheme.js
  docs/storybook/.storybook/main.js
  docs/storybook/.storybook/manager.js
  docs/storybook/.storybook/preview.js
  docs/storybook/README.md
  docs/storybook/package-lock.json
  docs/storybook/package.json
  docs/storybook/public/annotation_toolkit.svg
  docs/storybook/public/annotation_toolkit_grey_x2.png
  docs/storybook/public/annotation_toolkit_x1.png
  docs/storybook/public/annotation_toolkit_x2.png
  docs/storybook/public/favicon.ico
  docs/storybook/public/index.html
  docs/storybook/public/logo192.png
  docs/storybook/public/logo512.png
  docs/storybook/public/manifest.json
  docs/storybook/public/robots.txt
  docs/storybook/src/stories/Button.jsx
  docs/storybook/src/stories/Button.stories.jsx.bk
  docs/storybook/src/stories/Header.jsx
  docs/storybook/src/stories/Header.stories.jsx.bk
  docs/storybook/src/stories/InterpolatedBBox.stories.jsx
  docs/storybook/src/stories/Introduction.stories.mdx
  docs/storybook/src/stories/Keypoints.jsx
  docs/storybook/src/stories/Keypoints.stories.jsx
  docs/storybook/src/stories/Layers.stories.jsx
  docs/storybook/src/stories/Panels.stories.jsx
  docs/storybook/src/stories/VideoPlayer.stories.jsx
  docs/storybook/src/stories/Wrapper.jsx
  docs/storybook/src/stories/assets/annotation_toolkit_grey_x2.png
  docs/storybook/src/stories/assets/code-brackets.svg
  docs/storybook/src/stories/assets/colors.svg
  docs/storybook/src/stories/assets/comments.svg
  docs/storybook/src/stories/assets/direction.svg
  docs/storybook/src/stories/assets/flow.svg
  docs/storybook/src/stories/assets/plugin.svg
  docs/storybook/src/stories/assets/repo.svg
  docs/storybook/src/stories/assets/stackalt.svg
  docs/storybook/src/stories/button.css
  docs/storybook/src/stories/header.css
  docs/storybook/src/stories/keypoints.css
  docs/storybook/yarn.lock
  packages/annotation-toolkit/README.md
Labels: CLA Signed, annotation-toolkit, ui

#507 Silencing direct inits from Database classes
  mephisto/abstractions/databases/local_database.py
Labels: CLA Signed

#509 Enable symlinking js bundle via Hydra prop to make for easier local development for static_react_task
  examples/static_react_task/README.md
  examples/static_react_task/hydra_configs/conf/example.yaml
  mephisto/abstractions/architects/local_architect.py
  mephisto/abstractions/architects/router/deploy/package-lock.json
  mephisto/abstractions/blueprints/abstract/static_task/static_blueprint.py
  mephisto/abstractions/blueprints/static_react_task/static_react_blueprint.py
  mephisto/abstractions/blueprints/static_react_task/static_react_task_builder.py
Labels: CLA Signed

#478 annotation-toolkit v1.1.2 - Adds the MovableRect component
  packages/annotation-toolkit/README.md
  packages/annotation-toolkit/package.json
  packages/annotation-toolkit/release-notes.md
  packages/annotation-toolkit/src/helpers.js
  packages/annotation-toolkit/src/index.css
  packages/annotation-toolkit/src/index.js
  packages/annotation-toolkit/src/layers/MovableRect.js
  packages/annotation-toolkit/src/layers/RRRR/README.md
  packages/annotation-toolkit/src/layers/RRRR/Rect/index.js
  packages/annotation-toolkit/src/layers/RRRR/index.js
  packages/annotation-toolkit/src/layers/RRRR/react-rect.css
  packages/annotation-toolkit/src/layers/RRRR/utils.js
  packages/annotation-toolkit/src/layers/VideoPlayer.js
  packages/annotation-toolkit/src/panels/ContentPanel.js
  packages/annotation-toolkit/src/panels/DebugPanel.js
  packages/annotation-toolkit/yarn.lock
  packages/global-context-store/package.json
Labels: CLA Signed, annotation-toolkit
