Repository facebookresearch/Mephisto, pull requests merged in 2022-04, with the labels that each got.

#739 Fix trigger for `npm-check` workflow
  .github/workflows/npm-check.yml
Labels: CLA Signed

#743 [fix] Update `style-loader` to unbreak UI builds w/ newer webpack
  examples/parlai_chat_task_demo/webapp/package-lock.json
  examples/parlai_chat_task_demo/webapp/package.json
  examples/static_react_task/webapp/package-lock.json
  examples/static_react_task/webapp/package.json
  mephisto/abstractions/blueprints/static_html_task/source/package-lock.json
  mephisto/abstractions/blueprints/static_html_task/source/package.json
Labels: bug, CLA Signed, ui/ux

#745 Adding assert to static tasks for data type
  mephisto/abstractions/blueprints/abstract/static_task/static_agent_state.py
  mephisto/operations/client_io_handler.py
Labels: CLA Signed

#754 Remove prometheus/grafana executables from docker context
  .dockerignore
Labels: CLA Signed, fix

#755 Update black version in pre-commit check
  .pre-commit-config.yaml
Labels: CLA Signed

#747 Adding reasonable defaults to our examples for max concurrent units
  examples/parlai_chat_task_demo/hydra_configs/conf/base.yaml
  examples/remote_procedure/mnist/hydra_configs/conf/launch_with_local.yaml
  examples/remote_procedure/template/hydra_configs/conf/launch_with_local.yaml
  examples/simple_static_task/hydra_configs/conf/example.yaml
  examples/simple_static_task/hydra_configs/conf/onboarding_example.yaml
  examples/static_react_task/hydra_configs/conf/example.yaml
  examples/static_react_task/hydra_configs/conf/onboarding_example.yaml
Labels: CLA Signed

#756 Fixing static html onboarding->in_task script refresh
  mephisto/abstractions/blueprints/static_html_task/source/dev/app.jsx
Labels: CLA Signed

#762 Locking node version to 16 current for EC2Architect
  mephisto/abstractions/architects/ec2/run_scripts/node/init_server.sh
  mephisto/operations/operator.py
Labels: CLA Signed

#763 Fixing issue with remote procedure agent state preventing reload
  mephisto/abstractions/blueprints/remote_procedure/remote_procedure_agent_state.py
Labels: CLA Signed

#765 Fixed minor dependency
  mephisto/scripts/mturk/launch_makeup_hits.py
Labels: CLA Signed

#767 Fixed issue in updating credentials file
  mephisto/abstractions/providers/mturk/mturk_utils.py
Labels: CLA Signed

#769 Onboarding + Shutdown cleanup fixes
  mephisto/data_model/agent.py
  mephisto/operations/client_io_handler.py
  mephisto/operations/worker_pool.py
Labels: CLA Signed
