Repository facebookresearch/Mephisto, pull requests merged in 2022-07, with the labels that each got.

#809 Updates contributing.md with info on pre-commit
  CONTRIBUTING.md
Labels: CLA Signed

#810 Adds ability to set custom task lifetime
  mephisto/abstractions/providers/mturk/mturk_unit.py
  mephisto/abstractions/providers/mturk/mturk_utils.py
  mephisto/data_model/task_run.py
Labels: CLA Signed

#814 Consolidating AgentState metadata
  mephisto/abstractions/_subcomponents/agent_state.py
  mephisto/abstractions/blueprints/abstract/static_task/static_agent_state.py
  mephisto/abstractions/blueprints/mock/mock_agent_state.py
  mephisto/abstractions/blueprints/parlai_chat/parlai_chat_agent_state.py
  mephisto/abstractions/blueprints/remote_procedure/remote_procedure_agent_state.py
  mephisto/abstractions/database.py
  mephisto/abstractions/databases/local_database.py
  mephisto/data_model/agent.py
  mephisto/operations/client_io_handler.py
Labels: CLA Signed

#795 Add tests for static_react_task example
  .github/workflows/cypress-end-to-end-tests.yml
  CONTRIBUTING.md
  examples/remote_procedure/mnist/run_task.py
  examples/remote_procedure/mnist/webapp/package-lock.json
  examples/remote_procedure/template/run_task.py
  examples/remote_procedure/template/webapp/package-lock.json
  examples/remote_procedure/toxicity_detection/run_task.py
  examples/remote_procedure/toxicity_detection/webapp/package.json
  examples/remote_procedure/toxicity_detection/webapp/src/app.jsx
  examples/static_react_task/README.md
  examples/static_react_task/run_task.py
  examples/static_react_task/webapp/cypress.config.js
  examples/static_react_task/webapp/cypress/e2e/static_react_task.cy.js
  examples/static_react_task/webapp/cypress/fixtures/example.json
  examples/static_react_task/webapp/cypress/support/commands.js
  examples/static_react_task/webapp/cypress/support/e2e.js
  examples/static_react_task/webapp/link_mephisto_task.sh
  examples/static_react_task/webapp/package-lock.json
  examples/static_react_task/webapp/package.json
  examples/static_react_task/webapp/src/components/core_components.jsx
  mephisto/data_model/task_run.py
  mephisto/tools/scripts.py
Labels: CLA Signed, dependencies

#819 Adds info on blueprint vars to react-task readme
  examples/static_react_task/README.md
Labels: CLA Signed

#826 change Mephisto directory typo
  docs/web/docs/guides/quickstart.md
Labels: CLA Signed

#779 Embracing Poetry: includes version + deps bump
  .github/workflows/python-test.yml
  .gitignore
  MANIFEST.in
  docs/web/docs/guides/quickstart.md
  mephisto/VERSION
  package.json
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  setup.py
  yarn.lock
Labels: CLA Signed

#800 Add tests for remote examples
  .github/workflows/cypress-end-to-end-tests.yml
  examples/remote_procedure/mnist/webapp/cypress.config.js
  examples/remote_procedure/mnist/webapp/cypress/e2e/remote_procedure_mnist.cy.js
  examples/remote_procedure/mnist/webapp/link_mephisto_task.sh
  examples/remote_procedure/mnist/webapp/package-lock.json
  examples/remote_procedure/mnist/webapp/package.json
  examples/remote_procedure/mnist/webapp/src/components/core_components.jsx
  examples/remote_procedure/template/webapp/cypress.config.js
  examples/remote_procedure/template/webapp/cypress/e2e/remote_procedure_template.cy.js
  examples/remote_procedure/template/webapp/link_mephisto_task.sh
  examples/remote_procedure/template/webapp/package-lock.json
  examples/remote_procedure/template/webapp/package.json
  examples/remote_procedure/template/webapp/src/components/core_components.jsx
  examples/remote_procedure/toxicity_detection/webapp/cypress.config.js
  examples/remote_procedure/toxicity_detection/webapp/cypress/e2e/remote_procedure_toxicity_detection.cy.js
  examples/remote_procedure/toxicity_detection/webapp/link_mephisto_task.sh
  examples/remote_procedure/toxicity_detection/webapp/package-lock.json
  examples/remote_procedure/toxicity_detection/webapp/package.json
  examples/remote_procedure/toxicity_detection/webapp/src/components/core_components.jsx
  examples/static_react_task_with_tips/webapp/src/components/core_components.jsx
  examples/static_react_task_with_tips/webapp/src/css/style.css
Labels: CLA Signed

#831 ScreenTaskRequred -> ScreenTaskRequired
  docs/web/docs/guides/how_to_use/worker_quality/using_screen_units.md
Labels: CLA Signed

#824 heroku architect: fix default git branch name
  mephisto/abstractions/architects/heroku_architect.py
Labels: CLA Signed

#834 Improves performance of cypress tests
  examples/remote_procedure/mnist/webapp/cypress/e2e/remote_procedure_mnist.cy.js
  examples/remote_procedure/template/webapp/cypress/e2e/remote_procedure_template.cy.js
  examples/remote_procedure/toxicity_detection/webapp/cypress/e2e/remote_procedure_toxicity_detection.cy.js
  examples/static_react_task/webapp/cypress/e2e/static_react_task.cy.js
Labels: CLA Signed, fix

#832 Adds http:// before launch message url
  mephisto/abstractions/providers/mock/mock_unit.py
Labels: CLA Signed

#793 Add feedback component
  examples/static_react_task/webapp/package-lock.json
  examples/static_react_task_with_tips/webapp/package-lock.json
  examples/static_react_task_with_tips/webapp/src/components/core_components.jsx
  mephisto/abstractions/_subcomponents/agent_state.py
  mephisto/data_model/agent.py
  mephisto/scripts/local_db/review_feedback_for_task.py
  mephisto/scripts/local_db/review_tips_for_task.py
  mephisto/tools/data_browser.py
  packages/mephisto-task/build/bundle.js
  packages/mephisto-worker-addons/README.md
  packages/mephisto-worker-addons/src/Feedback/FeedbackTextArea.js
  packages/mephisto-worker-addons/src/Feedback/Question.js
  packages/mephisto-worker-addons/src/Feedback/SubmitButton.js
  packages/mephisto-worker-addons/src/Feedback/index.css
  packages/mephisto-worker-addons/src/Feedback/index.js
  packages/mephisto-worker-addons/src/Functions.js
  packages/mephisto-worker-addons/src/Reducers.js
  packages/mephisto-worker-addons/src/Tips/InfoIcon.js
  packages/mephisto-worker-addons/src/Tips/TaskTips.js
  packages/mephisto-worker-addons/src/Tips/UserSubmission.js
  packages/mephisto-worker-addons/src/Tips/index.js
  packages/mephisto-worker-addons/src/index.jsx
  pyproject.toml
Labels: CLA Signed

#836 Replace cli outputs with tables in docs
  docs/web/docs/guides/how_to_use/task_creation/developing_frontends.md
  docs/web/docs/guides/tutorials/custom_react.md
  docs/web/docs/guides/tutorials/first_task.md
Labels: CLA Signed

#837 Improves clarity of setting data folder in docs
  data/README.md
  docs/web/docs/guides/quickstart.md
Labels: CLA Signed

#813 Improve cli for tips review
  CONTRIBUTING.md
  mephisto/scripts/local_db/remove_accepted_tip.py
  mephisto/scripts/local_db/review_tips_for_task.py
  mephisto/tools/scripts.py
  mephisto/utils/rich.py
  pyproject.toml
Labels: CLA Signed, ui/ux

#820 Improve cli for mephisto wut
  mephisto/client/cli.py
  pyproject.toml
Labels: CLA Signed

#822 Improve cli for other mephisto commands
  docs/web/docs/guides/how_to_use/task_creation/developing_frontends.md
  docs/web/docs/guides/tutorials/custom_react.md
  docs/web/docs/guides/tutorials/first_task.md
  mephisto/client/cli.py
  mephisto/utils/rich.py
Labels: CLA Signed

#854 Upgrade to yarn 3.2.1
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/releases/yarn-3.0.2.cjs
  .yarn/releases/yarn-3.2.1.cjs
  .yarn/releases/yarn-berry.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: CLA Signed

#840 Fixing cli bugs with mephisto web and mephisto review
  mephisto/client/cli.py
  mephisto/client/full/server.py
  pyproject.toml
Labels: CLA Signed

#855 Update mephisto-task and mephisto-worker-addons pkg version number
  examples/parlai_chat_task_demo/webapp/package.json
  examples/remote_procedure/mnist/webapp/package.json
  examples/remote_procedure/template/webapp/package.json
  examples/remote_procedure/toxicity_detection/webapp/package.json
  examples/static_react_task/webapp/package.json
  examples/static_react_task_with_tips/hydra_configs/conf/example.yaml
  examples/static_react_task_with_tips/webapp/package.json
  mephisto/abstractions/architects/router/build_router.py
  mephisto/abstractions/architects/router/flask/mephisto_flask_blueprint.py
  mephisto/abstractions/architects/router/node/server.js
  mephisto/abstractions/blueprints/parlai_chat/webapp/package.json
  mephisto/abstractions/blueprints/static_html_task/source/package.json
  packages/mephisto-task/build/bundle.js
  packages/mephisto-task/package.json
  packages/mephisto-worker-addons/package.json
  yarn.lock
Labels: CLA Signed

#841 Adds a new cli command, 'scripts'
  mephisto/client/cli.py
Labels: CLA Signed

#859 Fixing bug in ParlAI agent state from 1.0.2
  mephisto/VERSION
  mephisto/abstractions/blueprints/parlai_chat/parlai_chat_agent_state.py
  pyproject.toml
Labels: CLA Signed

#860 Adds cypress section to frontend docs
  docs/web/docs/guides/how_to_contribute/frontend_development.md
Labels: CLA Signed

#838 Adds tips/feedback section to docs
  docs/web/docs/guides/how_to_contribute/_category_.yml
  docs/web/docs/guides/how_to_use/task_creation/_category_.yml
  docs/web/docs/guides/how_to_use/task_creation/developing_frontends.md
  docs/web/docs/guides/how_to_use/worker_experience/_category_.yml
  docs/web/docs/guides/how_to_use/worker_experience/feedback.md
  docs/web/docs/guides/how_to_use/worker_experience/mephisto-worker-addons.md
  docs/web/docs/guides/how_to_use/worker_experience/tips.md
  docs/web/docs/guides/how_to_use/worker_quality/_category_.yml
  docs/web/docs/reference/overview.md
  docs/web/static/feedback_component.png
  docs/web/static/tips_component.png
  packages/mephisto-task/README.md
Labels: CLA Signed

#833 Add tests to tips example
  .github/workflows/cypress-end-to-end-tests.yml
  examples/remote_procedure/toxicity_detection/webapp/cypress/e2e/remote_procedure_toxicity_detection.cy.js
  examples/static_react_task_with_tips/assets/tips.csv
  examples/static_react_task_with_tips/webapp/cypress.config.js
  examples/static_react_task_with_tips/webapp/cypress/e2e/post_submission_tests/static_react_task_with_tips_post_tip_submission.cy.js
  examples/static_react_task_with_tips/webapp/cypress/e2e/pre_submission_tests/0-static_react_task_with_tips_pre_tip_submission.cy.js
  examples/static_react_task_with_tips/webapp/cypress/e2e/pre_submission_tests/1-static_react_task_with_tips_feedback_submission.cy.js
  examples/static_react_task_with_tips/webapp/cypress/helper.js
  examples/static_react_task_with_tips/webapp/cypress/support/commands.js
  examples/static_react_task_with_tips/webapp/cypress/support/e2e.js
  examples/static_react_task_with_tips/webapp/package-lock.json
  examples/static_react_task_with_tips/webapp/package.json
  mephisto/scripts/local_db/gh_actions/expire_all_units.py
  packages/annotated/dev-scripts/bin/dev-scripts.js
  packages/mephisto-worker-addons/package.json
  yarn.lock
Labels: CLA Signed

#858 Add searchbar to docs
  docs/web/docusaurus.config.js
  docs/web/package.json
  docs/web/src/css/custom.css
  docs/web/src/pages/index.js
  docs/web/src/pages/index.module.css
  yarn.lock
Labels: documentation, CLA Signed

#861 Make `self.metadata` backward-compatible
  mephisto/abstractions/blueprints/parlai_chat/parlai_chat_agent_state.py
Labels: CLA Signed

#863 Update searchbar colors
  docs/web/docusaurus.config.js
  docs/web/src/css/custom.css
Labels: CLA Signed

#864 fix breaks in create_validation_function for screening units
  mephisto/abstractions/blueprints/mixins/screen_task_required.py
Labels: CLA Signed

#857 Add path filter
  .github/workflows/cypress-end-to-end-tests.yml
Labels: CLA Signed

#866 Revert "Add path filter"
  .github/workflows/cypress-end-to-end-tests.yml
Labels: CLA Signed

#868 Add path filter
  .github/workflows/cypress-end-to-end-tests.yml
Labels: CLA Signed
